"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Constants = void 0;
exports.Constants = {
    public: {
        Enums: {
            app_permission: [
                "package_orders.create",
                "orders.update",
                "user_roles.read",
                "user_roles.update",
                "package_orders.update",
                "package_orders.read",
                "documents.read",
                "deliveries.create",
                "deliveries.read",
                "deliveries.update",
                "users.read",
                "users.read.admin",
                "users.read.superadmin",
                "users.update.admin",
                "users.update.superadmin",
                "vendors.manage",
                "vendors.read",
                "orders.manage",
                "orders.read",
                "vendor_outlets.manage",
                "vendor_outlets.read",
                "order_points.read",
                "order_points.manage",
                "recurring_orders.manage",
                "system_configuration.read",
                "system_configuration.manage",
                "my_user.update",
            ],
            app_role: ["superadmin", "admin", "vendor", "rider", "customer"],
            availability_status: ["online", "offline"],
            business_identification_type: [
                "CAC",
                "utility",
                "NIN",
                "drivers_licence",
                "international_passport",
                "voters_card",
            ],
            business_status: ["pending", "verified", "suspended"],
            business_subscriptions_status: ["pending", "success", "failed"],
            business_verification_status: ["pending", "verified", "rejected"],
            coupon_applicable_users: ["customer", "vendor", "rider", "admin"],
            coupon_service: ["discovery", "dispatch"],
            coupon_status: ["active", "expired", "disabled"],
            coupon_type: ["fixed", "percentage", "flat"],
            delivery_status: [
                "assigned",
                "accepted",
                "picked_up",
                "completed",
                "cancelled",
                "on_pick_up_route",
                "at_pick_up",
                "delivering",
                "delivered",
                "on_hold",
                "confirmed",
            ],
            discovery_rules_type: ["pricing"],
            discovery_type: ["customer", "business"],
            inventory_status: ["pending", "verified"],
            order_category: ["on_demand", "scheduled", "recurring"],
            order_delivery_status_type: [
                "pending",
                "accepted",
                "assigned",
                "delivering",
                "on_hold",
                "completed",
                "cancelled",
                "at_pick_up",
                "picked_up",
                "on_pick_up_route",
                "delivered",
                "confirmed",
                "cancel-request",
            ],
            order_point_type: ["pickup", "dropoff", "mapped"],
            order_status: [
                "pending",
                "accepted",
                "preparing",
                "ready_for_pickup",
                "delivering",
                "completed",
                "cancelled",
            ],
            package_order_status: [
                "pending",
                "accepted",
                "assigned",
                "delivering",
                "on_hold",
                "completed",
                "cancelled",
                "at_pick_up",
                "picked_up",
                "on_pick_up_route",
                "delivered",
                "cancel-request",
            ],
            pending_vendor_status: ["pending", "rejected", "approved"],
            recurring_frequency: [
                "daily",
                "weekly",
                "bi-weekly",
                "monthly",
                "quarterly",
            ],
            role_type: ["admin", "customer", "vendor"],
            rules_type: ["fuel", "service", "document"],
            system_configuration_parameter: ["pricing", "email", "notifications"],
            transaction_type: [
                "fund",
                "withdraw",
                "debt",
                "dispatch",
                "dispatch-refund",
            ],
            vehicle_assignment_status: ["assigned", "unassigned", "suspended"],
            vehicle_document_type: ["insurance", "roadworthiness", "licence"],
            vehicle_fuel_payment_method: ["cash", "card", "transfer"],
            vehicle_service_type: [
                "oil",
                "tyre",
                "brake",
                "inspection",
                "general",
                "tubes",
                "chain_socket",
            ],
            vehicle_status: ["active", "repair", "inactive"],
            vendor_payment_status: ["pending", "approved", "declined"],
            vendor_status: [
                "verified",
                "unverified",
                "requested_verification",
                "pending_verification",
            ],
        },
    },
};
